name: Create new release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        working-directory: web

      - name: Run build script
        run: bun run build
        working-directory: web

      - name: Update tag
        uses: EndBug/latest-tag@v1
        with:
          ref: ${{ github.ref_name }}

      - name: Install zip
        run: sudo apt install zip

      - name: Bundle files
        run: |
          mkdir -p ./temp/ac_scoreboard
          mkdir -p ./temp/ac_scoreboard/web/
          cp ./{LICENSE,README.md,fxmanifest.lua,config.lua} ./temp/ac_scoreboard
          cp -r ./{locales,modules,resource} ./temp/ac_scoreboard
          cp -r ./web/build ./temp/ac_scoreboard/web/
          cd ./temp && zip -r ../ac_scoreboard.zip ./ac_scoreboard

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          prerelease: false
          files: ac_scoreboard.zip
